### ISSUE TITLE
SSL doesn't seem to work

### ISSUE THREAD

**Issue by eukara** [anthonyc-r/TalkSoup#1]
Trying irc.libera.chat on port 6697 results in a code LIBIRC_ERR_TERMINATED message. Same with my own IRC server and bouncer. Is there a certain way you need to tell it to use SSL perhaps or did something break recently with libircclient perhaps?

**Comment by eukara** [comment]
libircclient wants you to prefix it with a pound (#) sign in an irc_connect() call apparently, however I get the #[addressofwhateverserver] not found with that. Very odd.

**Comment by anthonyc-r** [comment]
Yeah, to be honest I couldn’t figure out how to get it to work at the time. I don’t think I tried particularly hard though, so I’ll dig around and see if I can find anything.

**Comment by anthonyc-r** [comment]
Interestingly, I get the ‘SSL initialization failed’ message. (Arch linux x86_64). The ‘irctest’ example program that comes with the libircclient sources also fails with this same error. I’m testing using freenode on 6697.

I guess finding out any more will involve debugging libircclient.

**Comment by eukara** [comment]
I compiled it manually with the patches from [gentoo's package](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-libs/libircclient/files) and I do get irctest to print out

> Could not connect or I/O error: SSL certificate verify failed

So some SSL breakage must have occured, I get this on every server I try too.
Either way, not an issue of this project. but maybe leave it open for visibility in case somebody wants to tackle a patch for libircclient?

**Comment by anthonyc-r** [comment]
Hm, having removed that nonsense error check at ssl.c:130 (SSL_OP_NO_SSLv2 is defined as 0… it seems the gentoo patch addresses this) I’m able to connect to libera on port 6697 via this app.

As an additional note, I’m prepending the # at line 83 LibircclientInput.m. If you instead just add the # when setting up the server in the config gui - you do get the host not found message. It makes sense to add a checkbox to pick whether ssl is enabled when adding a server I think.

**Comment by eukara** [comment]
Hell yeah, got it working on my end!

I also had to fix it not passing over the password field. That was really important to getting it working with my bouncer (bip).

**Comment by anthonyc-r** [comment]
I’ve fixed the password not being passed through, and have added a checkbox to the server editor to control whether SSL is enabled (whether to prepend the # or not) on the master branch.

**Comment by anthonyc-r** [comment]
Also updated the readme in case anyone else encounters the ssl init failure error.
